import 'package:flutter/widgets.dart';

/// Exact code-point bridge for every Phosphor class used by prototype.html.
///
/// The upstream Flutter wrapper currently extends Flutter's final [IconData]
/// class and cannot compile on Flutter 3.44. We still depend on its official
/// font assets, and bind the code points generated by the same package.
abstract final class HaloIcon {
  static final Map<String, IconData> _prototypeIcons = {
    'ph ph-arrow-bend-up-right': IconData(
      0xe026,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-arrow-up': IconData(
      0xe08e,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-arrows-clockwise': IconData(
      0xe094,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-at': IconData(
      0xe0ac,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-bell-slash': IconData(
      0xe0d4,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-bell': IconData(
      0xe0ce,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-brackets-curly': IconData(
      0xe860,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-brain': IconData(
      0xe74e,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-broom': IconData(
      0xec54,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-calendar-check': IconData(
      0xe712,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-camera': IconData(
      0xe10e,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-camera-rotate': IconData(
      0xe7a4,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-caret-left': IconData(
      0xe138,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-caret-right': IconData(
      0xe13a,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-chat-circle-dots': IconData(
      0xe16c,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-chat-circle-text': IconData(
      0xe16e,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-check-circle': IconData(
      0xe184,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-circle': IconData(
      0xe18a,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-circles-three': IconData(
      0xe192,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-copy': IconData(
      0xe1ca,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-cpu': IconData(
      0xe610,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-cube': IconData(
      0xe1da,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-cubes': IconData(
      0xec7c,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-database': IconData(
      0xe1de,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-desktop-tower': IconData(
      0xe562,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-device-mobile': IconData(
      0xe1e0,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-dots-three': IconData(
      0xe1fe,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-download-simple': IconData(
      0xe20c,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-export': IconData(
      0xeaf0,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-eye': IconData(
      0xe220,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-eye-slash': IconData(
      0xe224,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-file': IconData(
      0xe230,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-file-text': IconData(
      0xe23a,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-file-zip': IconData(
      0xe958,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-files': IconData(
      0xe710,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-gear-six': IconData(
      0xe272,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-github-logo': IconData(
      0xe576,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-globe': IconData(
      0xe288,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-google-logo': IconData(
      0xe292,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-hard-drives': IconData(
      0xe2a0,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-image': IconData(
      0xe2ca,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-images': IconData(
      0xe836,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-info': IconData(
      0xe2ce,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-key': IconData(
      0xe2d6,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-link': IconData(
      0xe2e2,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-lock-key': IconData(
      0xe2fe,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-lock-simple': IconData(
      0xe308,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-magnifying-glass': IconData(
      0xe30c,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-markdown-logo': IconData(
      0xe508,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-microphone': IconData(
      0xe326,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-microphone-slash': IconData(
      0xe328,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-moon-stars': IconData(
      0xe58e,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-note': IconData(
      0xe348,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-open-ai-logo': IconData(
      0xe7d2,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-path': IconData(
      0xe39c,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-pause-circle': IconData(
      0xe3a0,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-phone': IconData(
      0xe3b8,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-phone-disconnect': IconData(
      0xe3bc,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-play-circle': IconData(
      0xe3d2,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-play-fill': IconData(
      0xe3d0,
      fontFamily: 'PhosphorFill',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-plugs': IconData(
      0xeb56,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-plugs-connected': IconData(
      0xeb5a,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-plus': IconData(
      0xe3d4,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-push-pin': IconData(
      0xe3e2,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-pulse': IconData(
      0xe000,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-power': IconData(
      0xe3da,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-question': IconData(
      0xe3e8,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-scan': IconData(
      0xebb6,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-share-network': IconData(
      0xe408,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-shield-check': IconData(
      0xe40c,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-sliders-horizontal': IconData(
      0xe434,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-sparkle': IconData(
      0xe6a2,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-speaker-high': IconData(
      0xe44a,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-square': IconData(
      0xe45e,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-squares-four': IconData(
      0xe464,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-stack': IconData(
      0xe466,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-stop-circle': IconData(
      0xe46e,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-storefront': IconData(
      0xe470,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-target': IconData(
      0xe47c,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-terminal-window': IconData(
      0xeae8,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-trash': IconData(
      0xe4a6,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-trend-up': IconData(
      0xe4ae,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-user-circle': IconData(
      0xe4c4,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-user': IconData(
      0xe4c2,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-user-minus': IconData(
      0xe4ce,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-user-plus': IconData(
      0xe4d0,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-users': IconData(
      0xe4d6,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-users-three': IconData(
      0xe68e,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-video-camera': IconData(
      0xe4da,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-warning': IconData(
      0xe4e0,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-warning-circle': IconData(
      0xe4e2,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-waveform': IconData(
      0xe802,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-wrench': IconData(
      0xe5d4,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-x': IconData(
      0xe4f6,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
    'ph ph-x-circle': IconData(
      0xe4f8,
      fontFamily: 'PhosphorRegular',
      fontPackage: 'phosphor_flutter',
    ),
  };

  static IconData? fromPrototypeClass(String className) {
    return _prototypeIcons[className.trim()];
  }

  static IconData requirePrototypeClass(String className) {
    final icon = fromPrototypeClass(className);
    if (icon == null) {
      throw ArgumentError.value(
        className,
        'className',
        'Unknown Phosphor icon',
      );
    }
    return icon;
  }
}
